import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import { JetBrains_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className={jetBrainsMono.className}>
      <body className="min-h-screen flex flex-col">
        <Header />
        <div className="flex-1">
          <div className="min-h-screen px-10 py-5 bg-background text-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
