import type { Metadata } from "next";
import Container from "./components/Container";
import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="min-h-screen flex flex-col">
        <Header />
        <div className="flex-1">
          <Container>{children}</Container>
        </div>
      </body>
    </html>
  );
}
