import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="min-h-screen flex flex-col">
        <Header />
        <div className="flex-1">
          <div className="min-h-screen px-10 py-5 bg-linear-to-bl from-slate-300 to-slate-800">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
